
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ask
#    username: root
#    password: root

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#  mvc:
#    static-path-pattern: /static/**
l:
  blog:
    name: L
    title: HB
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://207.246.85.3:3306/demo
    username: root
    password: root
  redis:
    host: 207.246.85.3
    port: 6379
    jedis:
      pool:
        max-active: 8
mybatis:
  mapper-locations: classpath:mapper/*.xml
